name: Deploy Node.js & React to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and build frontend
        working-directory: client
        run: |
          npm install
          npm run build

      - name: Prepare deployment package
        run: |
          mkdir -p deploy
          cp -r server deploy/server
          cp -r client/dist deploy/client

      - name: Copy files to Azure VM via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "deploy/*"
          target: "/home/${{ secrets.AZURE_USER }}/app"

      - name: Deploy on Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd ~/app/server
            npm install
            pm2 restart index || pm2 start index.js --name index
            sudo rm -rf /var/www/html/*
            sudo cp -r ~/app/client/* /var/www/html/

      - name: Save deployment log
        run: |
          mkdir -p logs
          echo "Deployment run on: $(date)" > logs/deploy.log
          tar -czvf deploy_log.tar.gz logs
